volumes:
  db-data:

services:
  db:
    image: postgres:16.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      dockerfile: ./Dockerfile.migrations
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    environment:
      ENVIRONMENT: DEVELOPMENT
      PORT: 5050
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - migrations
    ports:
      - 5050:5050

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
