FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY ./scripts/ ./scripts/
COPY ./migrations/ ./migrations/

RUN chmod +x ./scripts/run_migrations.sh

ENTRYPOINT ["./scripts/run_migrations.sh"]

